### PR TITLE
Changed to Decimal, added pressure and radiation

### PR DESCRIPTION
**Pull request by soby**
In reference to https://github.com/coddingtonbear/python-measurement/issues/7

### CODE REVIEW

**Comment by codingjoe** [comment]
Hi @soby 

sorry for the delay. I really think it's a good idea to switch to decimals, since there are more precise.
Could you update your PR. I promise to review it :)

Thanks!
-Johannes

**Comment by soby** [comment]
@codingjoe sorry, to which field are you referring?

**Comment by codingjoe** [comment]
Sorry, I was at [django-measurements](https://github.com/coddingtonbear/django-measurement) in my head. It's based on this package. Anyhow, are you using Django by any chance? If not I would need to migrate that package too and that might take me a while...
I still think Decimals are the way to go.

**Comment by soby** [comment]
I'm using Django/DRF but I'm doing most of the functionality of django-measurements in a DRF serializer, backing it with regular Django DecimalFields

**Comment by codingjoe** [comment]
Ok @soby let's do this! I gotta need some help tho. First can you split this into separate PRs. I see that you also add new measures. I am happy to add them, but please in a separate PR.

Once that is done, I would welcome a second reviewer. Do you happen to have someone (at your company maybe) that want's to review this too?

Best
-Joe

**Comment by soby** [comment]
@codingjoe I'm the only one with this area of responsibility at my organization, sorry.

On the separate PRs, any particular reason why?

**Comment by codingjoe** [comment]
@soby I don't want to overcomplicate this, but separate features should be discussed and merged separately.

e.g.: Adding a new measure is something I can review quickly and release without being backwards incompatible.

**Comment by codingjoe** [comment]
Since there hasn't been an update for about a year I am closing this PR. Please let me know if you want to continue you work here. I am happy to reopen this PR.

**Pull request closed without merging**
