### PR TITLE
Switch to Decimal based values

### PR DESCRIPTION
**Pull request by codingjoe**

### CODE REVIEW

**Comment by gabn88** [comment]
This is a big one, but a necessary one. I started to look it through, but I saw that also the testcases are not inherited from TestMeasurementBase anymore and all Measurements (like Mass) are now not inherited from MeasureBase but from Measure instead. Any particular reason for this change?

**Comment by codingjoe** [comment]
Thanks for your kind words @gabn88 and I agree, this has been overdue.
You mentioned the inheritance structure. So the `MeasureBase` is now a meta class or type and not an object anymore. The custom meta class is used to construct the `Measurement` classes properly.
Anyhow, I need to do a LOT of documentation. I will make sure to address this point.

I'd like to get your opinion though. Should I leave the name `MeasureBase`? It does something different now, so maybe it's good to rename it. I kept the class `Measure` only for backwards compatibility, but maybe it's better to as well break here to make people aware of the changes. What do you think?

**Comment by gabn88** [comment]
In my opinion you are now doing two things in one commit, improving code for constructing the Measurement classes AND adding decimal values. This makes it harder to follow which change is for what for an outsider like me. 

I like the change from MeasureBase to Measure. It is perfectly defendable that way, I just wasn't aware of the reason for this change, hence why I asked :) 
As long as the tests pass, all should be fine. I'm currently very busy with some work on my part that is also overdue. Will try clone your branch next week and test it locally then. Thanks for the fast reply @codingjoe!

**Comment by codingjoe** [comment]
@gabn88 yes, you are right. Yet, this is not merely a refactoring. I wrote the whole library again from scratch.

Anyhow, I am at 100% test coverage now, also the doc tests pass and I wrote new documentation.
I believe what's left to do, is test manually as much as possible and maybe write migration documentation.

**Pull request merged**
